# Generated by Django 5.2.17 on 2026-10-05 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Player', max_length=12)),
                ('flag', models.CharField(default='us', max_length=8)),
                ('races', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('best_lap', models.FloatField(default=0.0)),
                ('master_volume', models.FloatField(default=1.0)),
                ('sfx_volume', models.FloatField(default=0.8)),
                ('music_volume', models.FloatField(default=0.6)),
                ('laps', models.PositiveSmallIntegerField(default=3)),
                ('steer_rate', models.FloatField(default=1.0)),
                ('invert_steer', models.BooleanField(default=False)),
                ('bot_aggression', models.CharField(default='Casual', max_length=16)),
                ('track_type', models.CharField(default='meadow_dirt', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
